name: Bedevere

on:
  workflow_call:
    inputs:
      sentry_dsn:
        required: true
        type: string
      gh_secrets:
        required: true
        type: string
      gh_auth:
        required: true
        type: string
      port:
        required: true
        type: number
    secrets:
      token:
        required: true
  
env:
  SENTRY_DSN: ${{ inputs.sentry_dsn }}
  GH_SECRETS: ${{ inputs.gh_secrets }}
  GH_AUTH: ${{ inputs.gh_auth }}
  PORT: ${{ inputs.port }}

jobs:
  bedevere:
    name: Pass input and secrets to my-action

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.9-dev"]

    steps:
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/setup-python@v2
        if: "!endsWith(matrix.python-version, '-dev')"
        with:
          python-version: ${{ matrix.python-version }}
      - uses: deadsnakes/action@v2.1.1
        if: endsWith(matrix.python-version, '-dev')
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: python3 -m pip install coverage -U pip -r dev-requirements.txt
      - name: Run the bot
        run: python3 -m bedevere   